[package]
name = "quackformers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[[example]]
# crate-type can't be (at the moment) be overriden for specific targets
# src/wasm_lib.rs forwards to src/lib.rs so that we can change from cdylib
# (that is needed while compiling natively) to staticlib (needed since the
# actual linking will be done via emcc
name = "quackformers"
path = "src/wasm_lib.rs"
crate-type = ["staticlib"]

[dependencies]
candle-core = "0.8.4"
candle-nn = "0.8.4"
candle-transformers = "0.8.4"
duckdb = { version = "1.2.2", features = [
    "vscalar",
    "vscalar-arrow",
    "vtab-arrow"
] }
duckdb-loadable-macros = "0.1.5"
hf-hub = { version = "0.4.2", default-features = false, features = ["rustls-tls", "ureq"] }
intel-mkl-src = "0.8.1"
libduckdb-sys = { version = "1.2.2", features = ["loadable-extension"] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokenizers = "0.13.2"

[target.'cfg(not(target_os = "windows"))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = { version = "0.9", features = ["vendored"] }

