# statically linking the C runtime on windows seems sensible?
[target.x86_64-pc-windows-msvc]
# rustflags = ["-Ctarget-feature=+crt-static"]

# For MinGW builds
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static-libgcc"]

[env]
OPENSSL_STATIC = "1"
OPENSSL_DIR = ""

[build]
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { features = ["accelerate"] }
candle-nn = { features = ["accelerate"] }
candle-transformers = { features = ["accelerate"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
candle-core = { features = ["mkl"] }
candle-nn = { features = ["mkl"] }
candle-transformers = { features = ["mkl"] }